package main.java.components;

import main.java.Game;
import main.java.components.eatable.Eatable;
import main.java.utilities.Coordinates;
import main.java.utilities.Movable;

import static main.java.utilities.Preconditions.ensure;
import static main.java.utilities.Preconditions.require;


/**
 * Final class representing a {@code House}. A {@code House} contains during the night all its {@link Peasant}
 * and then recreates them during the day.
 *
 * @author Sami Kabbaj
 * @author Salim Chaoui El Faiz
 *
 */
public final class House extends Element {

    //Constants
    private final int MAX_CAPACITY;
    private final static int DEFAULT_CREATION_GENERATED  = 2;

    //Peasant that have entered this night
    private int peasantEntered;
    //From the peasants that have entered this night, count the ones that have eaten enough
    private int peasantHasEatenEnough;
    //Contains the number of peasants to generate this day
    private int toGenerateThisDay;
    //During the day (morning), counts the number of peasants actually generated by this house
    private int peasantGenerated;


    /**
     * Constructor for {@code House}.
     *
     * @param coordinates  are the initial {@link Coordinates} of the {@code House}.
     * @param toGenerateThisDay is the initial number of {@link Peasant} to generate at the creation of the {@code House}.
     * @param max_capacity is the maximal number of {@link Peasant} that this {@code House} can contain, it is meant to
     *                     be a static constant that is chosen in {@link Game}.
     * @throws IllegalArgumentException if the given {@link Coordinates} are out of bound.
     */
    public House(Coordinates coordinates, int toGenerateThisDay, int max_capacity){
        require(coordinates.getX() >= 0 && coordinates.getX() <= Game.COLUMNS);
        require(coordinates.getY() > 0 && coordinates.getY() <= Game.COLUMNS);
        this.coordinates = coordinates;
        this.toGenerateThisDay = toGenerateThisDay;
        this.MAX_CAPACITY = max_capacity;
    }

    /**
     * Alternative constructor to {@code House} where only the {@link Coordinates} are specified.
     *
     * @param coordinates are the initial {@link Coordinates} of the {@code House}.
     * @throws IllegalArgumentException if the given {@link Coordinates} are out of bound.
     */
    public House(Coordinates coordinates){
        this(coordinates, DEFAULT_CREATION_GENERATED, 10);
    }

    /**
     * Getter for the number of {@link Peasant} that have entered this night.
     *
     * @return number of {@link Peasant} that have entered this night.
     */
    public int getPeasantEntered() {
        return peasantEntered;
    }

    /**
     * Getter for the number of {@link Peasant} that have eaten enough from the one that have entered this night.
     *
     * @return the number of {@link Peasant} that have eaten enough from the one that have entered this night.
     */
    public int getPeasantHasEatenEnough() {
        return peasantHasEatenEnough;
    }

    /**
     * Getter for the number of {@link Peasant} to generate this day.
     *
     * @return the number of {@link Peasant} to generate this day.
     */
    public int getToGenerateThisDay() {
        return toGenerateThisDay;
    }

    /**
     * Getter for the number of {@link Peasant} actually generated this day.
     *
     * @return the number of {@link Peasant} actually generated this day.
     */
    public int getPeasantGenerated() {
        return peasantGenerated;
    }

    /**
     * Informative function returning if this {@code House} can still generate and have to generate another {@link Peasant}
     * or if the number to generate has been reached.
     * This function is meant to be used only during the day ({@code HELIOS}).
     *
     * @return true if this {@code House} can generate more, false otherwise.
     * @throws IllegalStateException if the number of {@link Peasant} generated exceeds the maximal capacity
     * of this {@code House}.
     */
    public boolean canGenerate(){
        ensure(
                peasantGenerated <= MAX_CAPACITY,
                "State and content of house : " + this + ", is not coherent."
        );
        return peasantGenerated < toGenerateThisDay && peasantGenerated < MAX_CAPACITY;
    }

    /**
     * Informative function returning if all the {@link Peasant} linked to this {@code House} have entered into it.
     * This function is meant to be used only during the night ({@code ARTEMIS}).
     *
     * @return true if all the {@link Peasant} have entered, false otherwise.
     * @throws IllegalStateException if the number of {@link Peasant} that have entered is bigger than the number of ones
     * generated by this {@code House}.
     */
    public boolean isEveryoneSleeping(){
        ensure(
                peasantGenerated >= peasantEntered,
                "State and content of house : " + this + ", is not coherent."
        );
        return peasantEntered == peasantGenerated;
    }

    /**
     * Setter for the number of {@link Peasant} to generate this day. This function has, as a side effect, to reset the
     * other attributes.
     *
     * @param toGenerate is the number of {@link Peasant} that have to be generated this day. The parameter can exceed the
     *                   maximal capacity of the {@code House} but it will be rounded to that maximal capacity if so.
     * @throws IllegalStateException if at the end of the function, the number of {@link Peasant} to generate this day
     * is not coherent with the maximal capacity of this {@code House}.
     *
     */
    public void setToGenerateThisDay(int toGenerate){
        toGenerateThisDay = Math.min(MAX_CAPACITY, toGenerate);
        peasantEntered = 0;
        peasantGenerated = 0;
        peasantHasEatenEnough = 0;
        ensure(toGenerateThisDay <= MAX_CAPACITY, "State and content of house : " + this + ", is not coherent.");
    }

    /**
     * Generates a {@link Peasant} linked to this {@code House}.
     *
     * @return the new generated {@link Peasant}.
     */
    public Peasant generate(){
        peasantGenerated++;
        return new Peasant(coordinates.translated(0,1), this);
    }

    /**
     * This function is meant to be used, to be called by a {@link Peasant} and allows him to enter into his {@code House}.
     *
     * @param hasEatenEnough informs if the {@link Peasant} has eaten enough {@link Eatable} this day, to increment the
     *                       corresponding attributes.
     * @throws IllegalStateException if the number of {@link Peasant} that have eaten enough is bigger than the ones entered or that
     * the number of entered ones is bigger than the maximal capacity of this {@code House}.
     */
    public void enter(boolean hasEatenEnough){
        peasantEntered++;
        if(hasEatenEnough) peasantHasEatenEnough++;
        ensure(
                peasantHasEatenEnough <= peasantEntered && peasantEntered <= MAX_CAPACITY,
                "State and content of house : " + this + ", is not coherent."
        );
    }
}
